// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD204iBrFAvNuZFOfY7uhCq5dBO2RZHHy4',
    appId: '1:1035153418038:web:b157c250aa32dd5a523597',
    messagingSenderId: '1035153418038',
    projectId: 'essenyemek-db65c',
    authDomain: 'essenyemek-db65c.firebaseapp.com',
    storageBucket: 'essenyemek-db65c.firebasestorage.app',
    measurementId: 'G-37ZN59NZ1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOYi-iuTsTJY3Qwy72aDRIMN62kmwBVGQ',
    appId: '1:1035153418038:android:566df0e12516e1bc523597',
    messagingSenderId: '1035153418038',
    projectId: 'essenyemek-db65c',
    storageBucket: 'essenyemek-db65c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzJ0v0oVRJHmVdC5zMBcKfxY6dIqCJ4m8',
    appId: '1:1035153418038:ios:42d2a7520cab046e523597',
    messagingSenderId: '1035153418038',
    projectId: 'essenyemek-db65c',
    storageBucket: 'essenyemek-db65c.firebasestorage.app',
    iosBundleId: 'com.essenyemek',
  );
}
